Episode:
    type: object
    config:
        description: "A repository's episode"
        fields:
            id:
                type: "String!"
                description: "The id of the character."
            title:
                type: "String"
                description: "The name of the character."
            body:
                type: "String"
                description: "Body of an episode"
            user:
                type: "User"
                description: "Represents a creator (and owner) of an Episode."
